# Generated by Django 3.2.19 on 2023-06-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=100),
        ),
    ]
